first_name = input("What is your first name: ")
last_name = input("What is your last name: ")
print ("Hey, what's your first name? :" ,first_name )
print ("And your last name? :" ,last_name )
print ("Well, pleased to meet you,",first_name , last_name)